version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
    open-pull-requests-limit: 2
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
    open-pull-requests-limit: 2
    commit-message:
      prefix: chore
      include: scope
