# Metadata: 
#    Source:    https://github.com/SparebankenVest/team-idt-templates
#    Version:   1

# Please update directories and drop/include ecosystems as needed

version: 2
updates:
  - package-ecosystem: nuget
    schedule:
      interval: daily
      time: "08:00"
    open-pull-requests-limit: 2
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: npm
    schedule:
      interval: daily
      time: "08:00"
    open-pull-requests-limit: 2
    commit-message:
      prefix: chore
      include: scope
